### PR TITLE
Landing page, transitions, routing, editorconfig...

### PR DESCRIPTION
**Pull request by eHammarstrom**
This PR adds:

Routing,
EditorConfig,
And transition animations

### CODE REVIEW

**Review by joelklint — APPROVED** [review]
This is code is amazing! Who wrote this?

**Review by VictorWinberg — APPROVED** [review]
Looks really nice! 
A bit confusing logos imo, but I love the concept.

**Comment by Oscar-Rydh** [comment]
Cider Looks good to me, though Travis complains on some rake stuff

**Comment by Oscar-Rydh** [comment]
Code* Lul, swedish spell check

**Comment by eHammarstrom** [comment]
@Oscar-Rydh travis config is not defined in this PR, exists in master.

**Comment by Oscar-Rydh** [comment]
Alright! Now i just need to find the ok button for review on my phone

**Pull request merged**
