### PR TITLE
Possible frontend design

### PR DESCRIPTION
**Pull request by Mattemagikern**
During last nights coding event, we created a vague sketch of how the website may look like. This is the suggested design which I'd like to discuss and whether or not we should to go forward with it.
If we settle with this design I would like to start a discussion about main components and whether or not the components styling should be inside the component or in a separate .css file, I would suggest the former.

### CODE REVIEW

**Comment by Oscar-Rydh** [comment]
Looks nice

**Comment by ErikBjare** [comment]
I don't think we should merge binaries files such as this image into the repo.

Just create a new issue and add the image inline there, that way it would be easy to find for anyone wanting to participate in the design discussion. 

Regarding placement of CSS code, some should probably be in a global CSS file, some should be in individual components. (usually code should go in individual components and then be "upgraded" to the global file)

**Comment by VictorWinberg** [comment]
+1 @ErikBjare

**Comment by Mattemagikern** [comment]
agreed!

**Comment by ErikBjare** [comment]
Continues in https://github.com/Dsek-LTH/Website/issues/10

(this is done for precious backlinks)

**Pull request closed without merging**
